version: "3.8"

services:
  #************Mongo DB***************
  database_mongo:
    container_name: mongo_container
    image: mongodb/mongodb-community-server:5.0-ubuntu2004
    environment:
      MONGO_INITDB_ROOT_USERNAME: gifts
      MONGO_INITDB_ROOT_PASSWORD: gifts
      MONGO_INITDB_BIND_IP: 0.0.0.0
    ports:
      - 27017:27017
    volumes:
      - mongo_data:/data/db

  #************Backend***************
  backend_spring:
    container_name: spring_container
    build:
      context: ./ss-be
      dockerfile: Dockerfile
    ports:
      - 8443:8443
    depends_on:
      - database_mongo

  #************Frontend***************
  frontend_angular:
    container_name: angular_container
    build:
      context: ./ss-project
      dockerfile: Dockerfile
    ports:
      - 443:443
    depends_on:
      - backend_spring

volumes:
  mongo_data:
#copiare volume in cartella backup
#docker run --rm -v ss_mongo_data:/data/db -v $(pwd)/backup/mydir:/backup alpine tar czf /backup/mongo_backup.tar.gz -C /data/db .
#cancellare volume ss_mongo_data
#ricreare volume ss_mongo_data
#copiare volume backup nel volume creato
#docker run --rm -v ss_mongo_data:/data/db -v $(pwd)/backup/mydir:/backup alpine tar xzf /backup/mongo_backup.tar.gz -C /data/db

