name: Deploy Certificate and Key Files

on:
  push:
    branches:
      - master

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Set up certificate and key files
      run: |
        echo "${{ secrets.SERVER_CRT }}" > ss-project/my-cert.crt
        echo "${{ secrets.SERVER_CRT }}" > ss-be/src/main/resources/server.crt
        echo "${{ secrets.SERVER_KEY }}" > ss-project/my-cert.key
        echo "${{ secrets.SERVER_KEY }}" > ss-be/src/main/resources/server.key

    - name: Set up SSH private key for OVH access
      run: |
        mkdir -p ~/.ssh
        echo "${{ secrets.PRIVATE_KEY }}" > ~/.ssh/id_rsa
        chmod 600 ~/.ssh/id_rsa

    - name: Deploy certificate and key files to OVH server
      run: |
        scp -r -o StrictHostKeyChecking=no . ns-gateway@57.129.75.115:~/laura/ss/
